// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHFzLKAld2zhUraOMivTwEfNjjp4g6db8',
    appId: '1:382198822205:web:efeeb4d3bb8667a210c154',
    messagingSenderId: '382198822205',
    projectId: 'flutterfirebase-842b3',
    authDomain: 'flutterfirebase-842b3.firebaseapp.com',
    databaseURL: 'https://flutterfirebase-842b3-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfirebase-842b3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXih1r4Y1iQDeQFiiy8GdMHrmA5s4-sEc',
    appId: '1:382198822205:android:5257a1d807305a1c10c154',
    messagingSenderId: '382198822205',
    projectId: 'flutterfirebase-842b3',
    databaseURL: 'https://flutterfirebase-842b3-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfirebase-842b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDSyLXdIdmQcyFs_mGAVIJaH9ZSpgvdr8',
    appId: '1:382198822205:ios:2c713a67eaafa2a410c154',
    messagingSenderId: '382198822205',
    projectId: 'flutterfirebase-842b3',
    databaseURL: 'https://flutterfirebase-842b3-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfirebase-842b3.appspot.com',
    iosBundleId: 'com.example.firebaseFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDSyLXdIdmQcyFs_mGAVIJaH9ZSpgvdr8',
    appId: '1:382198822205:ios:2c713a67eaafa2a410c154',
    messagingSenderId: '382198822205',
    projectId: 'flutterfirebase-842b3',
    databaseURL: 'https://flutterfirebase-842b3-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfirebase-842b3.appspot.com',
    iosBundleId: 'com.example.firebaseFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHFzLKAld2zhUraOMivTwEfNjjp4g6db8',
    appId: '1:382198822205:web:962614ee0d3f24e810c154',
    messagingSenderId: '382198822205',
    projectId: 'flutterfirebase-842b3',
    authDomain: 'flutterfirebase-842b3.firebaseapp.com',
    databaseURL: 'https://flutterfirebase-842b3-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfirebase-842b3.appspot.com',
  );

}